<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useUiStore } from '../stores/ui.store'
import { useRadioStore } from '../stores/radio.store'
import { usePhrasesStore } from '../stores/phrases.store'
import IstanteIcon from './IstanteIcon.vue'
const ui=useUiStore(),router=useRouter(),radio=useRadioStore(),phrases=usePhrasesStore();const favorite=computed(()=>!!phrases.current?.favorite)
const fs=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.()
async function share(){const text=phrases.current?.text||'Istante';const data={title:'Istante',text:`${text}\n\nhttps://istante.ruslan-dzyuba.it`};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(data.text)}catch{}}
function collection(fav=false){ui.phraseFavoritesOnly=fav;ui.phrasesOpen=true}
async function toggleFavorite(){if(phrases.current)await phrases.toggleFavorite(phrases.current)}
</script>
<template><nav class="toolbar" aria-label="Comandi screensaver"><div class="toolbar-cluster"><div class="toolbar-group"><button class="icon-button collection-phone" aria-label="Apri la biblioteca delle frasi" title="La tua biblioteca" @click="collection(false)"><IstanteIcon name="collection"/></button><button class="icon-button" aria-label="Un altro pensiero" title="Un altro pensiero" @click="phrases.next"><IstanteIcon name="shuffle"/></button><button class="icon-button" :class="{active:favorite}" aria-label="Aggiungi ai preferiti" title="Aggiungi ai preferiti" @click="toggleFavorite"><IstanteIcon name="heart" :filled="favorite"/></button></div><span class="group-divider"/><div class="toolbar-group"><button class="icon-button" aria-label="Apri timer" title="Un tempo per te" @click="ui.timerOpen=true"><IstanteIcon name="clock"/></button><button class="icon-button" aria-label="Apri il calendario" title="Il tuo calendario" @click="router.push('/calendar')"><IstanteIcon name="calendar"/></button></div><span class="group-divider"/><div class="toolbar-group"><button class="icon-button" aria-label="Condividi il tuo istante" title="Condividi il tuo istante" @click="share"><IstanteIcon name="share"/></button><button class="icon-button fullscreen" aria-label="Schermo intero" title="Schermo intero" @click="fs"><IstanteIcon name="expand"/></button><button class="icon-button" aria-label="Impostazioni" title="Impostazioni" @click="router.push('/settings')"><IstanteIcon name="settings"/></button></div></div></nav></template>
<style scoped>
.toolbar{display:flex;align-items:center;justify-content:center}.toolbar-cluster{display:flex;align-items:center;gap:3px}.toolbar-group{display:flex;align-items:center;gap:1px}.group-divider{width:1px;height:22px;background:var(--line);margin:0 7px}.icon-button{width:42px;height:42px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;flex-shrink:0;color:var(--muted);background:transparent;border:0;transition:background .2s,color .2s,transform .2s}.icon-button:hover{color:var(--ink);background:var(--accent-soft)}.icon-button:active{transform:scale(.93)}.icon-button.active{color:var(--accent)}.collection-phone{display:none}@media(max-width:740px){.toolbar-cluster{gap:0}.icon-button{width:40px;height:40px}.group-divider{margin:0 2px;height:18px}.collection-phone{display:inline-flex}.fullscreen{display:none}}@media(max-width:380px){.icon-button{width:37px;height:40px}.group-divider{display:none}}
</style>
