<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useUiStore } from '../stores/ui.store'
import { useRadioStore } from '../stores/radio.store'
import { usePhrasesStore } from '../stores/phrases.store'
const ui=useUiStore(),router=useRouter(),radio=useRadioStore(),phrases=usePhrasesStore()
const fs=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.()
async function share(){const text=phrases.current?.text||'Istante';const data={title:'Istante',text:`${text}\n\nhttps://istante.ruslan-dzyuba.it`};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(data.text)}catch{}}
function collection(fav=false){ui.phraseFavoritesOnly=fav;ui.phrasesOpen=true}
</script><template><nav class="toolbar glass" aria-label="Azioni Istante"><button class="tool collection" title="Raccolta" @click="collection(false)">⌘</button><button class="tool" title="Radio" @click="ui.radioOpen=true">♫<i v-if="radio.playing"/></button><button class="tool favorites" title="Preferiti" @click="collection(true)">♡</button><button class="tool" title="Timer" @click="ui.timerOpen=true">◷</button><button class="tool" title="Calendario" @click="router.push('/calendar')">▦</button><button class="tool share" title="Condividi" @click="share">↗</button><button class="tool fullscreen" title="Schermo intero" @click="fs">⛶</button><button class="tool" title="Impostazioni" @click="router.push('/settings')">⚙</button></nav></template><style scoped>.toolbar{display:grid;grid-template-columns:repeat(8,48px);gap:.2rem;padding:.35rem;border-radius:999px}.tool{position:relative;width:48px;height:48px;border:0;background:transparent;color:var(--text-secondary);border-radius:50%;font-size:1.25rem;cursor:pointer;transition:.18s}.tool:hover{background:rgba(255,255,255,.1);color:var(--text-primary)}.tool i{position:absolute;width:6px;height:6px;border-radius:50%;background:var(--success);right:7px;top:7px}@media(max-width:600px){.toolbar{grid-template-columns:repeat(6,46px)}.tool{width:46px;height:46px}.fullscreen,.collection{display:none}}@media(max-width:370px){.toolbar{grid-template-columns:repeat(5,44px)}.share{display:none}.tool{width:44px;height:44px}}</style>