<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useSettingsStore } from '../stores/settings.store'
import { moonPhase,solarTimes } from '../services/astronomy'
const s=useSettingsStore(),now=ref(new Date());let id=0
onMounted(()=>id=window.setInterval(()=>now.value=new Date(),30000));onBeforeUnmount(()=>clearInterval(id))
const astro=computed(()=>{const n=now.value,lat=s.data.latitude,lon=s.data.longitude;let rise=new Date(n),set=new Date(n);if(lat!=null&&lon!=null){const t=solarTimes(n,lat,lon);rise=t.sunrise;set=t.sunset}else{rise.setHours(6,30,0,0);set.setHours(18,30,0,0)}const isDay=+n>=+rise&&+n<+set;let p:number;if(isDay)p=(+n-+rise)/Math.max(1,+set-+rise);else{const nightStart=+n<+rise?+set-86400000:+set;const nextRise=+n<+rise?+rise:+rise+86400000;p=(+n-nightStart)/Math.max(1,nextRise-nightStart)}p=Math.max(0,Math.min(1,p));return{isDay,p,rise,set,phase:moonPhase(n)}})
const style=computed(()=>({left:`${6+88*astro.value.p}%`,top:`${64-48*Math.sin(Math.PI*astro.value.p)}%`}))
const times=computed(()=>`${astro.value.rise.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})} · ${astro.value.set.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`)
</script>
<template><div class="astronomy" aria-hidden="true"><div v-if="!astro.isDay" class="stars"><i v-for="n in 18" :key="n" :style="{left:`${(n*37)%96}%`,top:`${(n*53)%70}%`,opacity:String(.25+(n%5)*.12)}"/></div><div class="orb" :class="astro.isDay?'sun':'moon'" :style="style"><span v-if="!astro.isDay" :style="{'--phase':astro.phase}"/></div><div class="sun-times">{{times}}</div></div></template>
<style scoped>.astronomy{position:absolute;inset:0;z-index:1;pointer-events:none;overflow:hidden}.orb{position:absolute;transform:translate(-50%,-50%);width:clamp(64px,7vw,150px);aspect-ratio:1;border-radius:50%;opacity:.78;transition:left 20s linear,top 20s linear}.sun{background:radial-gradient(circle at 42% 42%,#fff7d0 0 12%,#f2d99d 38%,rgba(238,200,126,.42) 58%,rgba(238,200,126,0) 72%);filter:blur(.1px);box-shadow:0 0 60px rgba(247,220,156,.25)}.moon{width:clamp(56px,6vw,132px);background:radial-gradient(circle at 35% 32%,#f2f2e7,#c6c8bf 62%,#8f958f);box-shadow:0 0 45px rgba(211,222,214,.15);overflow:hidden}.moon span{position:absolute;width:100%;height:100%;border-radius:50%;background:rgba(16,20,18,.48);transform:translateX(calc((var(--phase) - .5) * 95%))}.stars i{position:absolute;width:2px;height:2px;background:white;border-radius:50%;box-shadow:0 0 6px rgba(255,255,255,.7)}.sun-times{position:absolute;left:50%;bottom:calc(var(--safe-bottom) + 5.8rem);transform:translateX(-50%);font-size:.64rem;letter-spacing:.13em;color:var(--text-muted);opacity:.7}@media(max-width:600px){.orb{width:70px}.moon{width:62px}.sun-times{display:none}}:global(.family-display) .orb{width:180px}:global(.family-display) .moon{width:160px}</style>
