<script setup lang="ts">
import { computed } from 'vue'
import { usePhrasesStore } from '../stores/phrases.store'
const p=usePhrasesStore();const hour=computed(()=>new Date().getHours());const label=computed(()=>hour.value<12?'Il pensiero del mattino':hour.value<18?'Il pensiero del giorno':'Il pensiero della sera');const nextLabel=computed(()=>hour.value<12?'18:00':hour.value<18?'18:00':'06:00')
</script>
<template><section class="thought-block"><div class="thought-eyebrow"><span class="tiny-line"/><h1>{{label}}</h1><span class="tiny-line"/></div><figure class="quote-wrap"><blockquote>{{p.current?.text || 'Un momento, per te.'}}</blockquote></figure><div class="phrase-meta"><span class="status-dot"/> <span>Prossimo pensiero alle {{nextLabel}}</span></div></section></template>
<style scoped>
.thought-block{width:100%;max-width:1000px;margin:47px auto 0;text-align:center}.thought-eyebrow{display:flex;align-items:center;justify-content:center;gap:14px;color:var(--accent)}.thought-eyebrow h1{margin:0;font:500 10px/1.2 var(--sans);letter-spacing:.19em;text-transform:uppercase}.tiny-line{width:24px;height:1px;background:currentColor;opacity:.5}.quote-wrap{margin:23px auto 0;min-height:100px;display:flex;flex-direction:column;justify-content:center;max-width:870px}.quote-wrap blockquote{margin:0;font:400 clamp(27px,3.1vw,44px)/1.27 var(--serif);letter-spacing:-.025em;text-wrap:balance;overflow-wrap:break-word}.phrase-meta{display:flex;gap:8px;justify-content:center;align-items:center;flex-wrap:wrap;font:400 10px/1.2 var(--sans);color:var(--muted);letter-spacing:.02em;margin-top:20px;min-height:15px}.status-dot{height:4px;width:4px;background:var(--accent);border-radius:50%;display:inline-block}@media(max-width:740px){.thought-block{margin-top:18px}.thought-eyebrow{gap:8px}.thought-eyebrow h1{font-size:9px}.tiny-line{width:16px}.quote-wrap{margin-top:10px;min-height:58px}.quote-wrap blockquote{font-size:clamp(20px,5.8vw,29px);line-height:1.27}.phrase-meta{font-size:9px;margin-top:12px}}@media(max-width:740px) and (orientation:landscape){.thought-block{margin-top:8px}.quote-wrap{min-height:0}.quote-wrap blockquote{font-size:clamp(18px,4.2vw,28px)}.phrase-meta{margin-top:8px}}
</style>
