<script setup lang="ts">
import { computed } from 'vue'
import { useRadioStore } from '../stores/radio.store'
import { useUiStore } from '../stores/ui.store'
import IstanteIcon from './IstanteIcon.vue'
const radio=useRadioStore(),ui=useUiStore()
const status=computed(()=>radio.current?.name||'FluxFM | Chillhop')
async function toggle(){if(!radio.current&&radio.stations.length){const preferred=radio.stations.find(s=>s.id==='chillhop'&&s.streamUrl)||radio.stations.find(s=>s.enabled&&s.streamUrl);if(preferred)await radio.play(preferred);else radio.surprise()}else radio.toggle()}
</script>
<template><section class="radio-mini" aria-label="Radio lo-fi"><button class="radio-play" :aria-pressed="radio.playing" :aria-label="radio.playing?'Metti in pausa la radio':'Ascolta la radio'" @click="toggle"><IstanteIcon :name="radio.playing?'pause':'play'" :size="17"/></button><button class="radio-disclosure" @click="ui.radioOpen=true"><span class="radio-kicker">LO-FI RADIO <span class="radio-eq" :class="{on:radio.playing}"><i/><i/><i/></span></span><span class="radio-status">{{status}}</span></button><button class="radio-expand" aria-label="Apri controlli radio" @click="ui.radioOpen=true"><IstanteIcon name="chevron" :size="18"/></button></section></template>
<style scoped>
.radio-mini{display:flex;align-items:center;gap:8px;color:var(--ink)}.radio-play,.radio-expand,.radio-disclosure{border:0;background:transparent;color:inherit}.radio-play{width:42px;height:42px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;color:var(--accent);background:color-mix(in srgb,var(--surface) 36%,transparent);transition:.18s}.radio-play:hover{background:var(--accent-soft);transform:scale(1.03)}.radio-disclosure{display:flex;flex-direction:column;align-items:flex-start;gap:2px;padding:3px 2px;min-width:145px;text-align:left}.radio-kicker{font:600 10px/1.2 var(--sans);letter-spacing:.15em;color:var(--ink);white-space:nowrap}.radio-status{font:400 10px/1.25 var(--sans);color:var(--muted);max-width:190px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.radio-expand{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;color:var(--muted)}.radio-expand:hover{background:var(--accent-soft);color:var(--ink)}.radio-eq{display:inline-flex;align-items:flex-end;gap:1px;height:8px;margin-left:3px;opacity:.45}.radio-eq i{display:block;width:1px;height:3px;background:var(--accent)}.radio-eq.on i:nth-child(1){animation:eq .75s ease-in-out infinite alternate}.radio-eq.on i:nth-child(2){animation:eq 1s .15s ease-in-out infinite alternate}.radio-eq.on i:nth-child(3){animation:eq .62s .25s ease-in-out infinite alternate}@keyframes eq{to{height:8px}}@media(max-width:620px){.radio-disclosure{min-width:0}.radio-status{display:none}.radio-kicker{font-size:8.5px}.radio-expand{display:none}.radio-play{width:38px;height:38px}}
</style>
