/* Istante v4 · Vue component: CalendarSourcesDialog */
(function(){
  'use strict';
  const registry = window.IstanteVueComponents = window.IstanteVueComponents || {};
  registry.CalendarSourcesDialog = {
    name: 'CalendarSourcesDialog',
    template: `<dialog aria-labelledby="cal-sources-title" class="panel calendar-source-panel" id="cal-sources-dialog"><div class="panel-head"><div><p class="section-label">I giorni da portare con te</p><h2 id="cal-sources-title">I tuoi calendari.</h2></div><button aria-label="Chiudi" class="icon-button close-button" data-cal-close="" type="button"><span class="icon" data-icon="close"></span></button></div><div class="panel-content"><div class="calendar-import"><label class="secondary-button file-button"><span class="icon" data-icon="upload"></span>Importa file ICS<input accept=".ics,text/calendar" hidden="" id="cal-file" type="file"/></label><p class="field-note"><span id="cal-source-count">0</span> calendari salvati · puoi tenerne fino a 8 insieme.</p></div><form id="cal-url-form"><label class="stacked-label">Nome<input id="cal-source-name" maxlength="80" placeholder="Famiglia, lavoro, il mio tempo..." type="text"/></label><label class="stacked-label">Link ICS condiviso<input autocomplete="off" id="cal-url" placeholder="https://.../calendario.ics" spellcheck="false" type="url"/></label><p class="field-note">Link ICS HTTPS/webcal: Google Calendar, Outlook, iCloud e altri provider compatibili.</p><button class="primary-button" id="cal-connect" type="submit">Collega calendario</button></form><p class="calendar-privacy">I link privati possono contenere una chiave di accesso: vengono memorizzati in questo browser e, solo durante la sincronizzazione, inoltrati alla tua installazione di Istante tramite l’API ICS. Il server non li salva. Non condividerli. Sincronizzazione in sola lettura, ogni 30 minuti mentre la pagina è aperta.</p><div id="cal-source-manager"></div><p class="calendar-message" id="cal-message" role="status"></p></div><div class="panel-footer"><button class="text-button" data-cal-close="" type="button">Fatto</button></div></dialog>`
  };
})();
