/* Istante v4 · Vue component: CollectionEditDialog */
(function(){
  'use strict';
  const registry = window.IstanteVueComponents = window.IstanteVueComponents || {};
  registry.CollectionEditDialog = {
    name: 'CollectionEditDialog',
    template: `<dialog aria-labelledby="collection-edit-title" class="panel collection-edit-panel" id="collection-edit-dialog"><div class="panel-head"><div><p class="section-label">La tua raccolta</p><h2 id="collection-edit-title">Modifica raccolta.</h2><p class="collection-edit-meta" id="collection-edit-meta"></p></div><button aria-label="Chiudi" class="icon-button close-button" data-close="" type="button"><span class="icon" data-icon="close"></span></button></div><div class="panel-content collection-edit-content"><form class="collection-edit-meta-form" id="collection-edit-meta-form"><label class="stacked-label">Titolo<input maxlength="80" name="title" required="" type="text"/></label><div class="form-row"><label class="stacked-label">Categoria<input maxlength="40" name="category" type="text"/></label><label class="stacked-label">Descrizione<input maxlength="400" name="description" type="text"/></label></div><button class="text-button" type="submit">Salva dettagli</button></form><div class="collection-edit-add"><label class="stacked-label"><span>Aggiungi una frase</span><textarea id="collection-edit-phrase" maxlength="500" placeholder="Un pensiero alla volta…" rows="3"></textarea></label><button class="primary-button" id="collection-edit-add" type="button"><span class="icon" data-icon="plus"></span>Aggiungi frase</button></div><div class="collection-edit-list-head"><strong id="collection-edit-count">0 frasi</strong><span>Solo su questo dispositivo</span></div><ol class="collection-edit-list" id="collection-edit-list"></ol><p class="empty-state" id="collection-edit-empty">La raccolta è vuota. Aggiungi la prima frase.</p></div><div class="panel-footer"><button class="primary-button" data-close="" type="button">Fatto</button></div></dialog>`
  };
})();
