/* Istante v4 · Vue component: WelcomeDialog */
(function(){
  'use strict';
  const registry = window.IstanteVueComponents = window.IstanteVueComponents || {};
  registry.WelcomeDialog = {
    name: 'WelcomeDialog',
    template: `<dialog aria-labelledby="welcome-title" class="panel welcome-panel" id="welcome-dialog">
<div class="panel-head"><span class="section-label">Benvenuto nel tuo istante</span><button aria-label="Esplora senza guida" class="icon-button close-button" data-close="" type="button"><span class="icon" data-icon="close"></span></button></div>
<div class="panel-content welcome-content"><div aria-hidden="true" class="welcome-emblem"><img alt="" height="58" src="assets/icons/icon.svg" width="58"/><span class="welcome-orbit"></span></div><p class="welcome-eyebrow">Il tuo schermo può fare meno. E darti di più.</p><h2 id="welcome-title">Prenditi<br/> il tuo istante.</h2><p class="welcome-lead">Istante trasforma uno schermo acceso in un punto di calma: il tempo resta visibile, una frase ti accompagna, il cielo segue la giornata e il tuo prossimo traguardo rimane vicino senza diventare un'altra lista di cose da fare.</p><div class="welcome-promises"><p><span class="icon" data-icon="heart"></span><span><strong>Ti riporta al presente.</strong> Un pensiero, un timer e piccoli rituali aiutano a creare pause vere tra una cosa e l'altra.</span></p><p><span class="icon" data-icon="clock"></span><span><strong>Dà forma al tempo.</strong> Orologio, calendario, prossimo impegno e traguardi tengono vicino ciò che conta, senza trasformare lo schermo in una lista di notifiche.</span></p><p><span class="icon" data-icon="headphones"></span><span><strong>Crea la tua atmosfera.</strong> Musica lo-fi, suoni offline, luce, meteo e sfondi possono rendere una scrivania, un tablet o uno schermo dedicato un posto più piacevole.</span></p></div><p class="welcome-footnote">Puoi usarlo come dashboard, screensaver o piccolo angolo di decompressione. Le preferenze restano sul tuo dispositivo.</p></div><div class="panel-footer"><button class="text-button" data-close="" type="button">Esploro da solo</button><button class="primary-button" id="welcome-tour" type="button">Scopriamolo insieme<span class="icon" data-icon="arrow"></span></button></div></dialog>`
  };
})();
